# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('distance', models.FloatField()),
                ('repetitions', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='workout',
            name='date_workout',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='text',
            field=models.CharField(choices=[('fit', 'fitness'), ('car', 'cardio'), ('sil', 'trening si\u0142owy'), ('cas', 'cardio+trening si\u0142owy')], max_length=3),
        ),
        migrations.AddField(
            model_name='workoutdetails',
            name='workout_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fits.Workout'),
        ),
    ]
