# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fits', '0003_auto_20180323_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutdetails',
            name='workout_type',
        ),
        migrations.AddField(
            model_name='workout',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WorkoutDetails',
        ),
    ]
