# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fits', '0005_auto_20180330_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
